name: flutter_graphql_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  get: ^4.3.8
  get_it: ^7.2.0
  graphql: ^5.0.0
  infinite_scroll_pagination: ^3.1.0
  json_annotation: ^4.3.0
  rxdart: ^0.26.0
  shared_preferences: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
